# Generated by Django 5.1.2 on 2026-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_site", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="customertransaction",
            new_name="customer_si_custome_6d1c48_idx",
            old_name="customer_scored_idx",
        ),
    ]
